### ISSUE TITLE
Rock cleaner keeps working when powered and with water

### ISSUE THREAD

**Issue by medsal15** [Bartz24/SkyResources#52] opened 2017-02-17 15:00 UTC
Give a rock cleaner power and water. It will clean the air at the cost of 250mB and power no matter what. An incredibly fast way to get rid of water.

**Comment by Bartz24** [comment] 2017-02-18 01:33
I'm unable to reproduce this

**Comment by Bartz24** [comment] 2017-02-25 02:53
Fixed in next version

**Closed as completed** 2017-02-25 03:07 UTC
